# Generated by Django 5.1.6 on 2025-03-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='/media/default/default.jpg', upload_to='profile_pics/'),
        ),
    ]
